blockchain:
  # 区块链总开关
  enabled: true

  # 测试配置
  testing:
    mock-enabled: true
    mock-config:
      failure-rate: 0.1         # 10% 失败率
      delay-millis: 1000     # 延迟1秒
      reorg-enabled: false       # 是否模拟重组
      seed: 12345 # 随机数种子


database:
  name: blockcertify

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&allowPublicKeyRetrieval=true&autoReconnect=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
